import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import Sidebar from "@/components/Sidebar";
import { FolderProvider } from "@/components/FolderContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <FolderProvider>
        <html lang="en">
          <body className={`antialiased`}>
            <div className="flex">
              <Sidebar />
              {children}
            </div>
          </body>
        </html>
      </FolderProvider>
    </SessionWrapper>
  );
}
