import ClientLayout from "./ClientLayout";
import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="antialiased">
          <ClientLayout>{children}</ClientLayout>
        </body>
      </html>
    </SessionWrapper>
  );
}
